probabilistic_mapping:
  min_error_l: 0.1 #sensor model
  max_error_l: 0.6
  min_length: 1
  max_length: 6
  error_L: 0.2
  length_L: 4
  risk_factor: -2.0  #risk evaluation
  varience_incremental: 0.00025
  incremental_varience_on: false
  global_map/width: 6.0 #global map specs
  global_map/length: 6.0
  local_map/width: 2.0 #local map specs
  local_map/length: 2.0
  local_map/distance_to_area_center: 0
  global_map/resolution: 0.05
  rate: 3
