frequency: 50

transform_timeout: 0.01

two_d_mode: false
diagnostics_agg: true

#x     , y     , z,
#roll  , pitch , yaw,
#vx    , vy    , vz,
#vroll , vpitch, vyaw,
#ax    , ay    , az

odom0: odom/raw
odom0_config: [false, false, true,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]

odom0_differential: false
odom0_relative: false

odom1: /vins_estimator/odometry
odom1_config: [true, true, false,
               true, true, true,
               false, false, false,
               false, false, false,
               false, false, false]

odom1_differential: false
odom1_relative: false

imu0: /trunk_imu

# NOTE: If you find that your robot has x drift,
# the most likely candidate is the x'' (acceleration) fr$
# Just set it to false! (It's the first entry on the las$
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]

imu0_differential: false
imu0_relative: true

odom_frame: odom
base_link_frame: base
world_frame: odom
