knee_orientation : ">>"
pantograph_leg : false
max_linear_velocity_x : 0.5
max_linear_velocity_y : 0.25
max_angular_velocity_z : 1.2
com_x_translation : 0.0
com_y_translation : 0.0
swing_height : 0.14 #0.14
stance_depth : 0.0
stance_duration : 0.4 #0.4
nominal_height : 0.3 #0.25
