global_frame: laikago_gazebo/odom
rolling_window: false
track_unknown_space: true
map_topic: laikago_gazebo/odom
plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
