footprint: [[-0.5, -0.6], [-0.5, 0.6], [0.5, 0.6], [0.5, -0.6]]
footprint_padding: 0.001

robot_base_frame: base
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 6.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: odom
    subscribe_to_updates: true

obstacles_laser:
    observation_sources:  point_cloud_sensor  
    point_cloud_sensor: {sensor_frame: laser_link, clearing: true, topic: /aliengo/cloud1 , data_type: PointCloud2, marking: true,  min_obstacle_height: 0.3 ,max_obstacle_height: 0.7 }
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan1}
obstacles_laser_local:
    observation_sources:  point_cloud_sensor  
    point_cloud_sensor: {sensor_frame: laser_link, clearing: true, topic: /aliengo/cloud1 , data_type: PointCloud2, marking: true,  min_obstacle_height: 0.3 ,max_obstacle_height: 0.7 }
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan1}

grid_map_layer:
    observation_sources:  point_cloud_sensor  
    point_cloud_sensor: {sensor_frame: laser_link, clearing: true, topic: /traversable_map_visualization/traversability_points1, data_type: PointCloud2, marking: true,  min_obstacle_height: 0.0 , max_obstacle_height: 0.5 }
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan1}
inflation:
    inflation_radius: 0.2


